### ISSUE TITLE
[dev-task] Set up a home page where the user can view their feed

### ISSUE THREAD

**Issue by theogschool** [ShahzaibParacha/COMP-4350-Project#26]
After logging in, the user will be redirected to their home screen where they can view a feed from their subscribed channels. The user should also be able to share posts from here and create a qr code to share a post

https://github.com/ShahzaibParacha/COMP-4350-Project/issues/10: View posts on the home screen and be able to comment on posts, like and share posts
Priority: High

**Comment by ShahzaibParacha** [comment]
Implementation is complete for the home page, feeds will be added when we add functionality for posts.
